### ISSUE TITLE
Action never run

### ISSUE THREAD

**Issue by frixatrix** [arup-group/action-all-checks-passed#5]
Hi,

Tried to use your action but:
1. It has issue with `on: check_run ...` which I suppose should be `on:  check_run: ...`
2. Action never triggered and run, neither if running from your rep or mine.

Would appreciate some help to make this running if you still maintaining this repo, if not then stay safe and good luck!

**Comment by peterjgrainger** [comment]
I only worked this out recently....

This event is only triggered if the checks API is called https://docs.github.com/en/free-pro-team@latest/rest/guides/getting-started-with-the-checks-api

I noticed this when I was using Azure DevOps. If I used DevOps as a third party installed app, this check was triggered. If I used it just by connecting my own account it didn't get triggered.

However it never seemed to work 100% for me, I wish GitHub had this as standard :(

**Comment by frixatrix** [comment]
Figured out that I had no check_runs so this never triggered, even setup couple check-runs (long way with Jenkins and GH App) for test but developed a workaround to work with check statuses instead of check-runs.

Anyway thank you for this action, it was my first step towards Checks API and everything it brings with.
